project:
  type: website
  output-dir: docs
website:
  title: "homework assignment questions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - assignment 1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

